name: EX-2-ACTIONS

on:
  workflow_dispatch:

permissions: 
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloning the repo
        uses: actions/checkout@v4

      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "github.actions@github.com"

      - name: Create a new branch
        run: |
            git checkout -b test-${{github.run_id}}
      
      - name: Create a new .txt file
        run: |
            touch fisier.txt

      - name: Put info inside the file and commit the file
        run: |
            echo "RUN ID:  ${{github.run_id}}" > fisier.txt
            echo "ACTOR: ${{github.actor}}"  >> fisier.txt
            echo "REPOSITORY: ${{github.repository}}" >>fisier.txt
            git add fisier.txt
            git commit -m "added fisier.txt"
            git push origin test-${{github.run_id}}


      - name: Create PR with gh pr create
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
            gh pr create \
              --base main \
              --head test \
              --title "Example" \
              --body "PR created automatically by git actions" \
              --label "github-automation"
            
      
        

